#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#        username: nacos
#        password: nacos
#        #namespace: yc119res
#  application:
#    name: res-food
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/yc119res?serverTimeZone=UTC
#    #使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#server:
#  port: ${port:9001}
#
#logging:
#  level:
#    root: info
#    com.yc: info
#    org.springframework: info
#  file:
#    path: ./logs
#
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印mybatis-plus的sql语句

spring:
  cloud:
    sentinel:  #sentinel配置
      transport:
        port: 8719
        dashboard: localhost:8888
      eager: true
  sleuth:
    web:
      client:
        #开启采集链路
        enabled: true
    sampler:
      #默认采集是0.1(百分之十),生产环境采用默认，测试环境可以修改为1.0
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/


#等待队列的长度，默认100
server:
  tomcat:
    accept-count: 10
    #最大工作线程数
    max-threads: 20
    #最小工作空闲线程数，默认10
    min-spare-threads: 5
    #最大连接数，默认为10000
    max-connections: 100